version = 1

[[annotations]]
path = ["**/*.pdf", "**/*.pdfpc", "**/*.odp", ".github/FUNDING.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Thomas Perrot <thomas.perrot@tupi.fr>"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
